colo industry
set number
set smartindent
set ruler
set wildmenu wildmode=list:longest,full
set whichwrap+=h,l,<,>,[,],b,s
set backspace=indent,eol,start
set nostartofline
set virtualedit=block
set showmatch
set title
set cursorline
set laststatus=2
set cmdheight=2
set backupdir=~/.vim/backup
set undodir=~/.vim/undo
set confirm
set hidden
set autoread
set nobackup
set noswapfile
set hlsearch
set incsearch
set noignorecase
set smartcase
set wrapscan
set clipboard&
set clipboard=unnamedplus,autoselect
set scrolloff=8
set sidescrolloff=8
set sidescroll=1
set sw=4
set ts=4
set sw=4
set expandtab
helptags ~/.vim/doc/
set helplang=ja,en
