[[plugins]]
repo = 'Shougo/unite.vim'

#[[plugins]]
#repo = 'davidhalter/jedi-vim'
#on_ft = ['python']
#hook_source = '''
#autocmd FileType python setlocal completeopt-=preview
#hi Pmenu ctermbg=0 ctermfg=11
#hi PmenuSel ctermbg=8 ctermfg=11
#'''

[[plugins]]
    repo = 'alvan/vim-closetag'
    on_ft = ['html', 'xml']

#[[plugins]]
#    repo = 'zchee/deoplete-clang'
#    on_ft = ['c', 'cpp' , 'cmake']
#    hook_source = '''
#        let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-6.0/lib/libclang.so'
#        let g:deoplete#sources#clang#clang_header = '/usr/include/clang/6.0/include/'
#    '''
#    depends = ['deoplete.nvim']

#[[plugins]]
#    repo = 'zchee/deoplete-jedi'
#    on_ft = ['python']
#    hook_source = '''
#        let g:python3_host_prog = '/home/itachoco/.pyenv/shims/python3'
#        let g:deoplete#sources#jedi#python_path = '/home/itachoco/.pyenv/shims/python3'
#    '''

[[plugins]]
    repo = 'autozimu/LanguageClient-neovim'
    rev = 'next'
    depends = ['deoplete.nvim']
    build = 'bash install.sh'
    hook_add = '''
        set hidden
        let g:LanguageClient_serverCommands = {
            \'c' : ['clangd'],
            \'cpp': ['clangd'],
            \'python':['pyls']
        \}
        let g:LanguageClient_loadSettings = 1
        let g:LanguageClietn_hasSnippentSupport = 0

        set completefunc=LanguageClient#complete
    '''
    epends = ['deoplete.nvim']
    on_ft = ['c', 'cpp', 'cmake', 'python']

[[plugins]]
    repo = 'Shougo/neoinclude.vim'
    depends = ['deoplete.nvim']
    on_ft = ['c', 'cpp', 'python']
