[[plugins]]
    repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
    if has('win32')
        let cmd = 'tools\\update-dll-mingw'
    elseif has('win32unix')
        let cmd = 'make -f make_cygwin.mak'
    elseif executable('gmake')
        let cmd = 'gmake'
    else
        let cmd = 'make'
    endif
    let g:dein#plugin.build = cmd
'''

[[plugins]]
    repo = 'autozimu/LanguageClient-neovim'
    rev = 'next'
    build = 'bash install.sh'

    hook_add = '''
        set hidden
        let g:LanguageClient_serverCommands = {
            \'c' : ['clangd'],
            \'cpp': ['clangd', '-compile-commands-dir', '~/'],
            \'python':['pyls'],
            \'java' : ['jdtls']
        \}
        let g:LanguageClient_loadSettings = 1
        let g:LanguageClient_hasSnippetSupport = 0
        let g:LanguageClient_autoStart = 1
        let g:LanguageClient_usePopupHover = 1
        let g:LanguageClient_hoverPreview = 'Always'
        inoremap <silent><expr><C-j> LanguageClient#textDocument_hover()
        nnoremap <silent><C-r> :call LanguageClient#textDocument_rename()<CR>
        command! Def :call LanguageClient#textDocument_definition()

        set completefunc=deoplete#complete
    '''
    depends = ['deoplete.nvim']
    on_event = "VimEnter"

