[[plugins]]
    repo = 'Shougo/denite.nvim'
    on_event = "VimEnter"
    depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]]
    repo = 'Shougo/deoplete.nvim'
    on_event = "InsertEnter"
    hook_add = '''
        let g:deoplete#enable_at_startup = 1
        let g:deoplete#auto_complete_delay = 0
        let g:deoplete#auto_complete_start_length = 1
        let g:deoplete#enable_smart_case = 1
        let g:deoplete#file#enable_buffer_path = 1
        set completeopt-=preview
        "<C-Space>のマッピングをつぶす
        imap <buffer> <Nul> <C-Space>
        smap <buffer> <Nul> <C-Space>
        "<C-Space>で補完のポップアップを表示する。
        inoremap <silent><expr> <C-Space> pumvisible() ? deoplete#cancel_popup() : deoplete#manual_complete()
        "左右キーを使うとポップアップを消すことができる。
        inoremap <silent><expr> <Left>  Close_left()
        inoremap <silent><expr> <Right> Close_right()

        function! Close_left() abort
            call deoplete#smart_close_popup()
            return "\<Left>"
        endfunction

        function! Close_right() abort
            call deoplete#close_popup()
            return "\<Right>"
        endfunction
    '''

[[plugins]]
    repo = 'alvan/vim-closetag'
    on_ft = ['html', 'xml']

[[plugins]]
    repo = 'autozimu/LanguageClient-neovim'
    rev = 'next'
    depends = ['deoplete.nvim']
    build = 'bash install.sh'
    hook_add = '''
        set hidden
        let g:LanguageClient_serverCommands = {
            \'c' : ['clangd'],
            \'cpp': ['clangd'],
            \'python':['pyls']
        \}
        let g:LanguageClient_loadSettings = 1
        let g:LanguageClient_hasSnippetSupport = 0
        let g:LanguageClient_autoStart = 1
        let g:LanguageClient_hoverPreview = "Never"
        inoremap <silent><expr><C-j> LanguageClient#textDocument_signatureHelp()
        nnoremap <silent><C-r> :call LanguageClient#textDocument_rename()<CR>
        command! Def :call LanguageClient#textDocument_definition()

        set completefunc=deoplete#complete
    '''
    depends = ['deoplete.nvim']
    on_event = "VimEnter"

[[plugins]]
    repo = 'Shougo/neoinclude.vim'
    depends = ['deoplete.nvim']
    on_source = ['deoplete.nvim']
    on_event = "InsertEnter"

[[plugins]]
    repo = 'cohama/lexima.vim'
    hook_add = '''
        let g:lexima_nvim_accept_pum_with_enter = 1
    '''
    hook_post_source = '''
        let g:lexima_no_default_rules = 1
        call lexima#set_default_rules()
        call lexima#insmode#map_hook('before', '<CR>', '')
        inoremap <expr>"\<CR>" deoplete#pumvisible() ? "\<CR>" : deoplete#popup_close()

    '''
    on_event = "VimEnter"

