[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
    repo = 'Shougo/deoplete.nvim'
    on_event = "VimEnter"
    hook_add = '''
        let g:deoplete#enable_at_startup = 1
        let g:deoplete#auto_complete_delay = 0
        let g:deoplete#auto_complete_start_length = 1
        let g:deoplete#enable_smart_case = 1
        let g:deoplete#file#enable_buffer_path = 1
        set completeopt-=preview
        "<C-Space>のマッピングをつぶす
        imap <buffer> <Nul> <C-Space>
        smap <buffer> <Nul> <C-Space>
        "<C-Space>で補完のポップアップを表示する。
        inoremap <silent><expr> <C-Space> pumvisible() ? deoplete#smart_close_popup() : deoplete#manual_complete()
        "左右キーを使うとポップアップを消すことができる。
        inoremap <silent><expr> <Left>  Close_left()
        inoremap <silent><expr> <Right> Close_right()

        function! Close_left() abort
            call deoplete#smart_close_popup()
            return "\<Left>"
        endfunction

        function! Close_right() abort
            call deoplete#smart_close_popup()
            return "\<Right>"
        endfunction
    '''

[[plugins]]
    repo = 'alvan/vim-closetag'
    on_ft = ['html', 'xml']

[[plugins]]
    repo = 'autozimu/LanguageClient-neovim'
    rev = 'next'
    depends = ['deoplete.nvim']
    build = 'bash install.sh'
    hook_add = '''
        set hidden
        let g:LanguageClient_serverCommands = {
            \'c' : ['clangd'],
            \'cpp': ['clangd'],
            \'python':['pyls']
        \}
        let g:LanguageClient_loadSettings = 1
        let g:LanguageClient_hasSnippetSupport = 0

        set completefunc=deoplete#complete
    '''
    epends = ['deoplete.nvim']
    on_event = "VimEnter"

[[plugins]]
    repo = 'Shougo/neoinclude.vim'
    depends = ['deoplete.nvim']
    on_source = ['deoplete.nvim']
    on_event = "InsertEnter"

[[plugins]]
    repo = 'cohama/lexima.vim'
    hook_add = '''
        let g:lexima_nvim_accept_pum_with_enter = 1
    '''
    on_event = "VimEnter"

