[[plugins]]
    repo = 'Shougo/dein.vim'

[[plugins]]
    repo = 'roxma/vim-hug-neovim-rpc'
    hook_add = '''
        let g:python3_host_prog = $PYENV_ROOT . "/shims/python3"
        let g:pythonx_host_prog = $PYENV_ROOT . "/shims/python"
    '''
[[plugins]]
    repo = 'roxma/nvim-yarp'
    hook_add = '''
    '''
[[plugins]]
    repo = 'scrooloose/nerdtree'
    hook_add = '''
        let g:NERDTreeMouseMode = 1
        let g:NERDTreeShowHiden = 1
        nnoremap <silent>sd :NERDTreeToggle<CR>
        autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    '''
