#!/usr/bin/env sh

server='/home/itachoco/lsp'

java \
    -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=1044 \
    -Declipse.application=org.eclipse.jdt.ls.core.id1 \
    -Dosgi.bundles.defaultStartLevel=4 \
    -Declipse.product=org.eclipse.jdt.ls.core.product \
    -Dlog.protocol=true\
    -Dlog.level=ALL\
    -noverify \
    -Xms1G \
    -jar $server/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar \
    -configuration $server/eclipse.jdt.ls/config_linux/ \
    -data . \
    "$@"
