[[plugins]]
    repo = 'Shougo/dein.vim'
    hook_add = '''
        let g:python3_host_prog = $PYENV_ROOT . "/versions/3.7.3/bin/python"
        let g:pythonx_host_prog = $PYENV_ROOT . "/versions/3.7.3/bin/python"
    '''

[[plugins]]
    repo = 'roxma/vim-hug-neovim-rpc'
[[plugins]]
    repo = 'roxma/nvim-yarp'
